# Routes:

# 1)
###
GET http://localhost:3001/api

# 2)
###
GET http://localhost:3001/api/greet

# Parametros:

# 1)
###
GET http://localhost:3001/api/user/606e04ddf5e43646585ae761/todo/1

# 2)
###
GET http://localhost:3001/api/user/606e04ddf5e43646585ae761

# 3)
###
GET http://localhost:3001/api/flights/LAX-SFO

# 4)
###
GET http://localhost:3001/api/user/lol-lolesimo

# 5)
###
GET http://localhost:3001/api/user/606e04ddf5e43646585ae761.Pass

# 7)
###
GET http://localhost:3001/api/user/

# Callback triggers para enrutar parametros
# 1)
###
GET http://localhost:3001/api/trigger/user/606e04ddf5e43646585ae761
