# Routes:

# 1)
###
GET http://localhost:3001/api

# 2)
###
GET http://localhost:3001/api/greet

# Parametros:

# 1)
###
GET http://localhost:3001/api/user/1/todo/1

# 2)
###
GET http://localhost:3001/api/user/4255

# 3)
###
GET http://localhost:3001/api/flights/LAX-SFO

# 4)
###
GET http://localhost:3001/api/user/lol-lolesimo

# 5)
###
GET http://localhost:3001/api/user/1.Pass

# 6)
###
GET http://localhost:3001/api/user/1.Pass/todo/1


